name: Next Calendar Version
author: Harm Matthias Harms
runs:
  using: node20
  main: dist/index.js
description: Get the next calendar based version
branding:
  color: blue
  icon: calendar
inputs:
  token:
    description: The github action token
    required: true
  tag_prefix:
    description: "A prefix for the generated version tag"
    required: false
    default: ""
outputs:
  old_tag:
    description: The base tag used to generate the new version/tag
  old_version:
    description: The base version parsed from old_tag
  new_tag:
    description: The generated tag
  new_version:
    description: The generated version
